### ISSUE TITLE
Java version information confusing and update install fails!!! (IEP-223)

### ISSUE THREAD

**Issue by ammaree** [espressif/idf-eclipse-plugin#114]
I am using a Macbook Pro with latest Catalina installed
Eclipse is latest version 2020-06 (4.16.0) Build id: 20200615-1200
<img width="409" alt="Screenshot Eclipse" src="https://user-images.githubusercontent.com/3227544/91064954-3037bf80-e630-11ea-94a1-c99fa2fc53e4.png">

System Preferences - Java - Java Control Panel - General - About shows V8U261 (build 1.8.0_261-b12)
<img width="373" alt="Screenshot Java 1" src="https://user-images.githubusercontent.com/3227544/91065234-83aa0d80-e630-11ea-8cee-5da365d185cb.png">

%java --version shows 'java 14.0.1 2020-04-14 (build 14.0.1-7)'
<img width="586" alt="Screenshot Java 2" src="https://user-images.githubusercontent.com/3227544/91065392-b0f6bb80-e630-11ea-9b55-46a7294c4ac4.png">

Eclipse shows updates being available:
<img width="626" alt="Screenshot Eclipse update" src="https://user-images.githubusercontent.com/3227544/91065478-ce2b8a00-e630-11ea-9032-04a871f1cc83.png">

But the update fails with error info being:
<img width="1010" alt="Screenshot Eclipse fail" src="https://user-images.githubusercontent.com/3227544/91065521-e00d2d00-e630-11ea-84a4-956f9b22cd61.png">

Q1. What version of Java am I running?
Q2. If there is a newer version of java required and available, what is the version and where do I get it?
Q3. How do I fix the update install error so I can get OpenOCD debugging going?

Thanks

**Comment by ammaree** [comment]
I think I have resolved Q1 and Q2.

A1. I had both SE Runtime 8u261 and JDK 14.0.1 installed. I have now uninstalled SE Runtime 8u261 so the Control panel is not showing any more.

A2. I have downloaded and installed the minor update from 14.0.1 to 14.0.2

But the primary problem remain, how to get  OpenOCD installed and working. I have tried to uninstall and reinstall the Eclipse ESP IDF Plugin but now the install fails completely.

How can I completely remove all traces of the ESP IDF Plugin and reinstall from scratch?

**Comment by kolipakakondal** [comment]
Hi @ammaree 

We have fixed the OpenOCD issue with our latest release, please check this here https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.2.1

Please confirm once it's verified.

Thank you

**Comment by ammaree** [comment]
@kolipakakondal 
It is still not working, although the symptoms have changed.

I would like to reopen the issue and supply full details. How do I reopen?

**Comment by kolipakakondal** [comment]
@ammaree Could you please provide the error details?

**Comment by ammaree** [comment]
Basically started a completely clean installation, deleted Eclipse (application, .project, .cproject, .metadata/* etc) as well as /Users/andremaree/.eclipse and /Users/andremaree/.p2 directories

From command line, checked that compile works using idf.py build, all works with no errors.
Following instruction on Github installed all requisites:
* Single version of java 14.0.2
* Python 3.8 installed, although % python --version shows 2.7.16
* 2020-06 Eclipse, starts clean and recreates ~/.eclipse and ~/.p2 directories.
* git 2.28.0
* ESP-IDF 4.x master at ~/Dropbox/devs/ws/z-sdk/esp-idf

Installed plugin from the update site, no problem.
After eclipse restart, select Help -> ESP-IDF Tools Manager -> Install tools

Option 1:
---------
<img width="600" alt="Screenshot 2020-08-26 at 13 41 41" src="https://user-images.githubusercontent.com/3227544/91299764-714fe100-e7a2-11ea-948a-148d0eade654.png">

Result 1:
--------
<img width="1329" alt="Screenshot 2020-08-26 at 13 42 01" src="https://user-images.githubusercontent.com/3227544/91299828-8cbaec00-e7a2-11ea-8b82-54a5c529fb0a.png">

Option 2:
---------
<img width="599" alt="Screenshot 2020-08-26 at 13 43 42" src="https://user-images.githubusercontent.com/3227544/91299892-a825f700-e7a2-11ea-9d61-a60e18469097.png">

Result 2:
---------
<img width="689" alt="Screenshot 2020-08-26 at 13 44 02" src="https://user-images.githubusercontent.com/3227544/91299945-bd9b2100-e7a2-11ea-8998-2c7cf2f7a0d5.png">

Info on Python:
---------------
![Screenshot 2020-08-26 at 13 37 20](https://user-images.githubusercontent.com/3227544/91299993-cf7cc400-e7a2-11ea-9a13-8de0a3d19093.png)

**Comment by ammaree** [comment]
Just following a hunch I tried the menu option Eclipse -> Help -> Download & Configure ESP IDF.
Step 1:
<img width="852" alt="Screenshot 2020-08-26 at 14 13 54" src="https://user-images.githubusercontent.com/3227544/91302769-4451fd00-e7a7-11ea-8725-9c4f8f3742a9.png">

Step 2:
<img width="601" alt="Screenshot 2020-08-26 at 14 14 23" src="https://user-images.githubusercontent.com/3227544/91304579-01455900-e7aa-11ea-9de3-2e091fb947b7.png">

Step 3:
<img width="581" alt="Screenshot 2020-08-26 at 14 14 08" src="https://user-images.githubusercontent.com/3227544/91304668-276af900-e7aa-11ea-9d2b-348f7f369676.png">

Step 4:
<img width="1609" alt="Screenshot 2020-08-26 at 14 14 38" src="https://user-images.githubusercontent.com/3227544/91304713-3a7dc900-e7aa-11ea-9007-1ffa78925a5c.png">

What concerns me here is still using Python 2.7 although support will be dropped soon.

**Comment by kolipakakondal** [comment]
> OSError: [Errno 2] No such file or directory

This is the error that I could see from the console which is causing an issue while running i**df_tools.py install-python-env** command internally

This is could be because git was not part of the environment path. If not, can you set git to the environment path?

Can you run the below command from the idf path?
$ git describe --tags

**Comment by ammaree** [comment]
v4.3-dev-775-ge664a6b4c9

**Comment by kolipakakondal** [comment]
> ## Result 1:
> <img alt="Screenshot 2020-08-26 at 13 42 01" width="1329" src="https://user-images.githubusercontent.com/3227544/91299828-8cbaec00-e7a2-11ea-8b82-54a5c529fb0a.png">
> 

@projectgus  @igrr  Can you please help with this error?

**Comment by kolipakakondal** [comment]
Okay good, now you're able to install tools and proceed further right?

Let me check with the team on the Python version

**Comment by ammaree** [comment]
Here is the Python version error:
<img width="1612" alt="Screenshot 2020-08-26 at 15 41 15" src="https://user-images.githubusercontent.com/3227544/91310868-af550100-e7b2-11ea-9098-2fa8a1b0df86.png">

**Comment by ammaree** [comment]
A step further, next problem but not Python related. 

During the Debug As configuration, 1 field is not automatically populated.
<img width="1314" alt="Screenshot 2020-08-26 at 16 20 22" src="https://user-images.githubusercontent.com/3227544/91315796-66a04680-e7b8-11ea-8d75-ccd4959debb8.png">

Since I build firmware for a number of different ESP32 based devices, the name filled in is only correct for 1 model. In order to automate this, what variables should I use to automatically pick up the name from the CMake process?

Since my ESP-WROVER-KIT could be either the 1.8V or 3.3V version, how do I identify the correct version?
<img width="1317" alt="Screenshot 2020-08-26 at 16 21 08" src="https://user-images.githubusercontent.com/3227544/91316234-e29a8e80-e7b8-11ea-87bd-ba02bf226d35.png">

In case it helps with debugging, the 3rd config screen:
<img width="1314" alt="Screenshot 2020-08-26 at 16 21 49" src="https://user-images.githubusercontent.com/3227544/91316617-4f158d80-e7b9-11ea-8cdf-18c7872fdc6c.png">

Lastly, when I start the debug process, the following error occurs:
<img width="402" alt="Screenshot 2020-08-26 at 16 17 20" src="https://user-images.githubusercontent.com/3227544/91316323-f8a84f00-e7b8-11ea-8697-7f0f07cf66db.png">

And the Console output related to the error is:
<img width="838" alt="Screenshot 2020-08-26 at 16 17 39" src="https://user-images.githubusercontent.com/3227544/91316423-12e22d00-e7b9-11ea-9f94-40282b19410b.png">

Since it detects the processors and the dual cores correctly, it seems likely a small configuration/timing problem?

**Comment by ammaree** [comment]
@kolipakakondal 

Took the case off my ESP-WROVER-KIT and verified the module fitted. It is a 1.8V ESP32-WROVER (ESP32-D0WDQ6) so the selected board is correct.

**Comment by curiousmuch** [comment]
> A step further, next problem but not Python related.
> 
> During the Debug As configuration, 1 field is not automatically populated.
> <img alt="Screenshot 2020-08-26 at 16 20 22" width="1314" src="https://user-images.githubusercontent.com/3227544/91315796-66a04680-e7b8-11ea-8d75-ccd4959debb8.png">
> 
> Since I build firmware for a number of different ESP32 based devices, the name filled in is only correct for 1 model. In order to automate this, what variables should I use to automatically pick up the name from the CMake process?
> 
> Since my ESP-WROVER-KIT could be either the 1.8V or 3.3V version, how do I identify the correct version?
> <img alt="Screenshot 2020-08-26 at 16 21 08" width="1317" src="https://user-images.githubusercontent.com/3227544/91316234-e29a8e80-e7b8-11ea-87bd-ba02bf226d35.png">
> 
> In case it helps with debugging, the 3rd config screen:
> <img alt="Screenshot 2020-08-26 at 16 21 49" width="1314" src="https://user-images.githubusercontent.com/3227544/91316617-4f158d80-e7b9-11ea-8cdf-18c7872fdc6c.png">
> 
> Lastly, when I start the debug process, the following error occurs:
> <img alt="Screenshot 2020-08-26 at 16 17 20" width="402" src="https://user-images.githubusercontent.com/3227544/91316323-f8a84f00-e7b8-11ea-8697-7f0f07cf66db.png">
> 
> And the Console output related to the error is:
> <img alt="Screenshot 2020-08-26 at 16 17 39" width="838" src="https://user-images.githubusercontent.com/3227544/91316423-12e22d00-e7b9-11ea-9f94-40282b19410b.png">
> 
> Since it detects the processors and the dual cores correctly, it seems likely a small configuration/timing problem?

I'm seeing the same issue for debugging.

**Comment by kolipakakondal** [comment]
Hi @ammaree @curiousmuch 

Could you please try this local build and confirm https://github.com/espressif/idf-eclipse-plugin/issues/118#issuecomment-685305247

**Comment by kolipakakondal** [comment]
JTAG device loading issue got fixed with the v1.2.2

https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.2.2
